spring:
  application:
    name: SoundList
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soundlist-db?createDatabaseIfNotExist=true
    username: root
    password: matheus15!
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true